#!/usr/bin/env node

const fs = require("fs");
const path = require("path");
const readline = require("readline");

class ConfigSetup {
	constructor() {
		this.rl = readline.createInterface({
			input: process.stdin,
			output: process.stdout,
		});
	}

	async setupEnvironment() {
		console.log("🚀 Homelab Dashboard Environment Setup\n");
		console.log(
			"This wizard will help you set up your .env configuration files.\n"
		);

		const config = {
			// Server settings
			PORT: await this.ask("Server port (default: 3050): ", "3050"),
			NODE_ENV: await this.ask(
				"Environment (development/production) (default: development): ",
				"development"
			),

			// Client settings
			CLIENT_PORT: await this.ask(
				"Client port (default: 3000): ",
				"3000"
			),

			// Database
			DB_PATH: await this.ask(
				"Database path (default: ./server/data/homelab.db): ",
				"./server/data/homelab.db"
			),

			// Monitoring
			SYSTEM_UPDATE_INTERVAL: await this.ask(
				"System update interval in ms (default: 5000): ",
				"5000"
			),
			ENABLE_CPU_TEMPERATURE:
				(await this.ask(
					"Enable CPU temperature monitoring? (y/n) (default: y): ",
					"y"
				)) === "y"
					? "true"
					: "false",

			// Security
			CORS_ORIGIN:
				config.NODE_ENV === "production"
					? await this.ask(
							"CORS origin for production (default: false): ",
							"false"
					  )
					: "http://localhost:3000",

			// Websites to monitor
			DEFAULT_WEBSITES: await this.setupWebsites(),
		};

		// Generate URLs based on ports
		config.REACT_APP_API_BASE_URL = `http://localhost:${config.PORT}`;
		config.REACT_APP_SOCKET_URL = `http://localhost:${config.PORT}`;

		await this.writeConfigFiles(config);

		console.log("\n✅ Environment configuration completed!");
		console.log("\n📁 Created files:");
		console.log("  - .env (main configuration)");
		console.log("  - client/.env (client-specific settings)");
		console.log("  - server/.env (server-specific settings)");
		console.log(
			"\n🔧 You can edit these files manually to fine-tune your configuration."
		);
		console.log(
			'\n🚀 Run "npm run validate-env" to validate your configuration.'
		);

		this.rl.close();
	}

	async ask(question, defaultValue = "") {
		return new Promise((resolve) => {
			this.rl.question(question, (answer) => {
				resolve(answer.trim() || defaultValue);
			});
		});
	}

	async setupWebsites() {
		console.log("\n📡 Website Monitoring Setup");
		const websites = [];

		const addWebsite = await this.ask(
			"Do you want to add websites to monitor? (y/n): ",
			"n"
		);

		if (addWebsite.toLowerCase() === "y") {
			let addMore = true;

			while (addMore) {
				const name = await this.ask("Website name: ");
				const url = await this.ask(
					"Website URL (include http/https): "
				);

				if (name && url) {
					websites.push({ name, url });
					console.log(`✅ Added: ${name} - ${url}`);
				}

				const more = await this.ask(
					"Add another website? (y/n): ",
					"n"
				);
				addMore = more.toLowerCase() === "y";
			}
		}

		return JSON.stringify(websites);
	}

	async writeConfigFiles(config) {
		// Main .env file
		const mainEnv = this.generateMainEnv(config);
		fs.writeFileSync(".env", mainEnv);

		// Client .env file
		const clientEnv = this.generateClientEnv(config);
		fs.writeFileSync("client/.env", clientEnv);

		// Server .env file
		const serverEnv = this.generateServerEnv(config);
		fs.writeFileSync("server/.env", serverEnv);
	}

	generateMainEnv(config) {
		return `# ==================================
# HOMELAB DASHBOARD - MAIN CONFIGURATION
# ==================================
# Generated by setup wizard on ${new Date().toISOString()}

# ==================================
# SERVER CONFIGURATION
# ==================================
PORT=${config.PORT}
NODE_ENV=${config.NODE_ENV}
CORS_ORIGIN=${config.CORS_ORIGIN}

# ==================================
# CLIENT CONFIGURATION
# ==================================
CLIENT_PORT=${config.CLIENT_PORT}
REACT_APP_API_BASE_URL=${config.REACT_APP_API_BASE_URL}
REACT_APP_SOCKET_URL=${config.REACT_APP_SOCKET_URL}
REACT_APP_CHART_UPDATE_INTERVAL=5000
REACT_APP_DEFAULT_TIME_RANGE=60

# ==================================
# DATABASE CONFIGURATION
# ==================================
DB_PATH=${config.DB_PATH}

# ==================================
# MONITORING CONFIGURATION
# ==================================
SYSTEM_UPDATE_INTERVAL=${config.SYSTEM_UPDATE_INTERVAL}
WEBSITE_CHECK_TIMEOUT=5000
ENABLE_CPU_TEMPERATURE=${config.ENABLE_CPU_TEMPERATURE}
ENABLE_DISK_IO_MONITORING=false
ENABLE_PROCESS_MONITORING=false

# ==================================
# DEFAULT WEBSITES TO MONITOR
# ==================================
DEFAULT_WEBSITES=${config.DEFAULT_WEBSITES}

# ==================================
# SECURITY CONFIGURATION
# ==================================
ENABLE_HELMET=true
TRUST_PROXY=false

# ==================================
# LOGGING CONFIGURATION
# ==================================
LOG_LEVEL=info
ENABLE_DEBUG_LOGGING=false
`;
	}

	generateClientEnv(config) {
		return `# ==================================
# CLIENT-SPECIFIC CONFIGURATION
# ==================================
# Generated by setup wizard on ${new Date().toISOString()}

REACT_APP_API_BASE_URL=${config.REACT_APP_API_BASE_URL}
REACT_APP_SOCKET_URL=${config.REACT_APP_SOCKET_URL}
REACT_APP_CHART_UPDATE_INTERVAL=5000
REACT_APP_DEFAULT_TIME_RANGE=60

PORT=${config.CLIENT_PORT}
BROWSER=none
FAST_REFRESH=true
GENERATE_SOURCEMAP=true
`;
	}

	generateServerEnv(config) {
		return `# ==================================
# SERVER-SPECIFIC CONFIGURATION
# ==================================
# Generated by setup wizard on ${new Date().toISOString()}

PORT=${config.PORT}
NODE_ENV=${config.NODE_ENV}
DB_PATH=${config.DB_PATH.replace("./server/", "./")}
CORS_ORIGIN=${config.CORS_ORIGIN}
SYSTEM_UPDATE_INTERVAL=${config.SYSTEM_UPDATE_INTERVAL}
`;
	}
}

// Run the setup if called directly
if (require.main === module) {
	const setup = new ConfigSetup();
	setup.setupEnvironment().catch(console.error);
}

module.exports = ConfigSetup;
